### ISSUE TITLE
Access to image regression datasets

### ISSUE THREAD

**Issue by tongnie** [seai-lab/TorchSpatial#2]
Hi, I am greatly impressed by the quality of your work! I am curious as to when the image regression datasets (i.e., mosaics) will become publicly available for access? :)

**Comment by neminwu** [comment]
Hello,
Yes, the regression datasets will also be uploaded and shared on Figshare/Dropbox through the same link. This should be completed within the week, and we will keep you updated. Thank you.

**Comment by QianC95** [comment]
> Hi, I am greatly impressed by the quality of your work! I am curious as to when the image regression datasets (i.e., mosaics) will become publicly available for access? :)

Hi tongnie, you can access all image regression datasets via our [Figshare link](https://figshare.com/articles/dataset/LocBench/26026798).

**Comment by neminwu** [comment]
Hi @tongnie, we are going to close this issue, and please feel free to re-open the issue if you encounter any further problems or open a new issue if you have additional concerns. Thank you.

**Comment by tongnie** [comment]
Thank you for your prompt response @QianC95 @neminwu . I'm wondering where I can get access to the original image data that was used to generate the visual embedding? For example, the images of the mosaics dataset. Thanks again.

**Comment by neminwu** [comment]
> Thank you for your prompt response @QianC95 @neminwu . I'm wondering where I can get access to the original image data that was used to generate the visual embedding? For example, the images of the mosaics dataset. Thanks again.

The dataset benchmark in TorchSpatial is designed to evaluate the performance of different location encoders using the same set of pre-trained image embeddings. Unfortunately, we do not provide the original images. 

However, if you are interested, you can access the MOSAIKS dataset, which was originally collected and distributed by the Global Policy Laboratory, at the following link: [Global Policy Laboratory](https://www.globalpolicy.science/mosaiks). You can also refer to the paper by Rolf, Esther, et al., titled "A generalizable and accessible approach to machine learning with global satellite imagery," published in Nature Communications 12.1 (2021): 4392.

Similarly, raw images for the other datasets may also be found at their original sources. Thank you.
